using UnityEngine;

public class LastBoss : MonoBehaviour, IEnemyStatus
{
    public int damage = 3;
    public float moveSpeed = 2f;
    public float detectRadius = 12f;
    public float elasticity = 2f; // ã‚¸ãƒ£ãƒ³ãƒ—æ”»æ’ƒæ™‚ã®ä¼¸ç¸®æ€§

    [Header("ä½“åŠ›è¨­å®š")]
    public int maxHealth = 10;
    private int currentHealth;

    public int point = 50; // å€’ã—ãŸã¨ãã«ã‚‚ã‚‰ãˆã‚‹ãƒã‚¤ãƒ³ãƒˆ

    public int Damage { get; set; }
    public float MoveSpeed { get; set; }
    public float DetectRadius { get; set; }

    public float coolTime = 15f; // æ”»æ’ƒé–“éš”ï¼ˆç§’ï¼‰

    public GameObject enemyPrefab; // ç”Ÿæˆã™ã‚‹æ•µã®ãƒ—ãƒ¬ãƒãƒ–
    private float coolTimer = 0f;
    private float attackTimer = 0f; // æ”»æ’ƒæ™‚é–“
    private int attack_id = 0; // æ”»æ’ƒæ–¹æ³•ã‚’æŒ‡å®šã™ã‚‹id
    bool isJumped = false; // ã‚¸ãƒ£ãƒ³ãƒ—ã—ãŸã‹ã‚’ç®¡ç†ã™ã‚‹ãƒ•ãƒ©ã‚°
    bool isAttacking = false; // æ”»æ’ƒä¸­ã‹ã‚’åˆ¤æ–­ã™ã‚‹ãƒ•ãƒ©ã‚°
    private int attackCount = 0; // å¬å–šæ”»æ’ƒã®å›æ•°

    private Rigidbody2D rb;
    private Transform player;
    private SpriteRenderer sr;
    private Vector3 originalScale;

    private bool isGrounded = false;
    private int groundContactCount = 0;
    private bool isFacingRight = true;

    private GameObject enemy; 

    void Start()
    {
        Damage = damage;
        MoveSpeed = moveSpeed;
        DetectRadius = detectRadius;

        currentHealth = maxHealth;

        rb = GetComponent<Rigidbody2D>();

        sr = GetComponent<SpriteRenderer>(); // è¿½åŠ 
        originalScale = transform.localScale; // è¿½åŠ 

        // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Æ•ï¿½ï¿½ï¿½ï¿½Õ“Ë‚ğ–³ï¿½ï¿½ï¿½ï¿½ï¿½
        GameObject playerObj = GameObject.FindWithTag("Player");

        if (playerObj != null)
        {
            player = playerObj.transform; // Transformï¿½ÍƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ÌˆÊ’uï¿½ipositionï¿½jï¿½Aï¿½ï¿½]ï¿½irotationï¿½jï¿½Aï¿½Xï¿½Pï¿½[ï¿½ï¿½ï¿½iscaleï¿½jï¿½ï¿½ï¿½Ç—ï¿½
            Collider2D playerCol = playerObj.GetComponent<Collider2D>();
            Collider2D myCol = GetComponent<Collider2D>();
            if (playerCol != null && myCol != null)
            {
                Physics2D.IgnoreCollision(myCol, playerCol, true);
            }
        }
    }

    void FixedUpdate()
    {
        if (player == null || !isGrounded) return;

        // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ü‚Å‚Ì‹ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Z
        float distance = Vector2.Distance(transform.position, player.position);

        // ï¿½ï¿½ï¿½a detectRadius ï¿½È“ï¿½ï¿½È‚ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½xï¿½ï¿½ï¿½Wï¿½ÉŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÄˆÚ“ï¿½
        if (distance <= detectRadius)
        {
            //ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ãŒè¿‘ãã«ã„ã‚‹ã¨ãã€ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ ãŒå›å¾©ã™ã‚‹
            if (coolTimer != 0)
            {
                coolTimer -= Time.deltaTime;
            }

            //ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ ãŒ0.25ä»¥ä¸‹ã®ã¨ãã«ç§»å‹•åœæ­¢(æ”»æ’ƒå‰ã«0.25ç§’é–“åœæ­¢ã™ã‚‹)
            if (coolTimer <= 0.25)
            {
                //ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ ãŒ0ã‹ã¤ã€æ”»æ’ƒä¸­ã§ãªã„ã¨ã
                if (coolTimer <= 0 && isAttacking == false)
                {
                    attack_id = UnityEngine.Random.Range(0, 2); //æ”»æ’ƒæ–¹æ³•ã®æŠ½é¸

                    //ã‚¸ãƒ£ãƒ³ãƒ—æ”»æ’ƒã®ã¨ã
                    if (attack_id == 0)
                    {
                        //åœ°é¢ã®ä¸Šã«ã„ã‚‹ã‹ã¤ã€ã‚¸ãƒ£ãƒ³ãƒ—ã—ã¦ãªã„ã¨ã
                        if (isGrounded && !isJumped)
                        {

                            UnityEngine.Vector2 targetPos = new UnityEngine.Vector2(player.position.x, player.position.y + 100f);
                            UnityEngine.Vector2 dir = (targetPos - (UnityEngine.Vector2)transform.position).normalized;
                            dir.x *= 3.5f;
                            rb.AddForce(dir * 5f, ForceMode2D.Impulse);

                            isAttacking = true; // æ”»æ’ƒãƒ•ãƒ©ã‚°
                            isJumped = true; // ã‚¸ãƒ£ãƒ³ãƒ—ãƒ•ãƒ©ã‚°ã‚’ç«‹ã¦ã‚‹
                            isGrounded = false;
                        }
                    }
                    //å¬å–šæ”»æ’ƒã®ã¨ã
                    else if (attack_id == 1)
                    {
                        if (player.position.x <= rb.position.x)
                        {
                            isFacingRight = true;
                        }
                        else
                        {
                            isFacingRight = false;
                        }
                        attackTimer = 2f;
                        isAttacking = true;
                        attackCount = 0;
                    }
                }
            }
            else if (isGrounded) //ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ ä¸­ã€åœ°é¢ã®ä¸Šã«ã„ã‚‹ã¨ãã«ç§»å‹•ã™ã‚‹
            {
                Vector2 targetPos = new Vector2(player.position.x, rb.position.y); // yï¿½Í•Ï‚ï¿½ï¿½È‚ï¿½
                Vector2 newPos = Vector2.MoveTowards(rb.position, targetPos, moveSpeed * Time.fixedDeltaTime);
                rb.MovePosition(newPos);
            }

        }
        //æ”»æ’ƒä¸­
        if (isAttacking == true)
        {
            // ã‚¸ãƒ£ãƒ³ãƒ—æ”»æ’ƒæ™‚ã€åœ°é¢ã«è§¦ã‚Œã¦ã„ã‚‹ã¨ã
            if (attack_id == 0 && isGrounded)
            {
                //ã‚¸ãƒ£ãƒ³ãƒ—ä¸­ã®å ´åˆ
                if (isJumped)
                {
                    isJumped = false;
                    attackTimer = 0.75f; // æ”»æ’ƒæ™‚é–“ã‚’0.5ç§’ã¨ã™ã‚‹
                }
                //ç€åœ°ã—ã¦ã‹ã‚‰1.5ç§’ä»¥å†…ã®å ´åˆ
                else if (attackTimer > 0)
                {
                    attackTimer -= Time.deltaTime;

                    float scaleFactor = 1.0f + Mathf.Sin((0.75f - attackTimer)) * elasticity;
                    transform.localScale = new Vector3(originalScale.x * scaleFactor, originalScale.y / scaleFactor, originalScale.z);
                    transform.position = new Vector2(rb.position.x, rb.position.y - (originalScale.y / scaleFactor) / 5.0f);

                    // attackTimerç§’éããŸå ´åˆ
                    if (attackTimer <= 0)
                    {
                        transform.localScale = originalScale; // å…ƒã«æˆ»ã™
                        isAttacking = false; // æ”»æ’ƒçµ‚äº†
                        //ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ ãƒªã‚»ãƒƒãƒˆ
                        coolTimer = coolTime;

                    }
                }
            } else if (attack_id == 1)
            {
                if (attackTimer > 0)
                {
                    attackTimer -= Time.deltaTime;
                    
                    if(enemyPrefab != null)
                    {
                        if (attackTimer <= 2.0f)
                        {
                            if (attackTimer <= 1.6f)
                            {
                                if (attackTimer <= 1.2f)
                                {
                                    if (attackTimer <= 0.8f)
                                    {
                                        if (attackTimer <= 0.4f)
                                        {
                                            if (attackTimer > 0f)
                                            {
                                                if (attackCount == 4)
                                                {
                                                    if (isFacingRight)
                                                    {
                                                        enemy = Instantiate(enemyPrefab, new Vector3(rb.position.x - 2f, rb.position.y + 1f, 0f), Quaternion.identity);
                                                    }
                                                    else
                                                    {
                                                        enemy = Instantiate(enemyPrefab, new Vector3(rb.position.x + 2f, rb.position.y + 1f, 0f), Quaternion.identity);
                                                        FlyEnemy fe = enemy.GetComponent<FlyEnemy>();
                                                        fe.SetFacing(true);
                                                    }
                                                    attackCount = 5;
                                                }
                                            }


                                        }
                                        if (attackCount == 3)
                                        {
                                            if (isFacingRight)
                                            {
                                                enemy = Instantiate(enemyPrefab, new Vector3(rb.position.x - 2f, rb.position.y + 1f, 0f), Quaternion.identity);
                                            }
                                            else
                                            {
                                                enemy = Instantiate(enemyPrefab, new Vector3(rb.position.x + 2f, rb.position.y + 1f, 0f), Quaternion.identity);
                                                FlyEnemy fe = enemy.GetComponent<FlyEnemy>();
                                                fe.SetFacing(true);
                                            }
                                            attackCount = 4;

                                        }
                                    }
                                    if (attackCount == 2)
                                    {
                                        if (isFacingRight)
                                        {
                                            enemy = Instantiate(enemyPrefab, new Vector3(rb.position.x - 2f, rb.position.y, 0f), Quaternion.identity);
                                        }
                                        else
                                        {
                                            enemy = Instantiate(enemyPrefab, new Vector3(rb.position.x + 2f, rb.position.y, 0f), Quaternion.identity);
                                            FlyEnemy fe = enemy.GetComponent<FlyEnemy>();
                                            fe.SetFacing(true);
                                        }
                                        attackCount = 3;
                                    }
                                }
                                if (attackCount == 1)
                                {
                                    if (isFacingRight)
                                    {
                                        enemy = Instantiate(enemyPrefab, new Vector3(rb.position.x - 2f, rb.position.y - 1f, 0f), Quaternion.identity);
                                    }
                                    else
                                    {
                                        enemy = Instantiate(enemyPrefab, new Vector3(rb.position.x + 2f, rb.position.y - 1f, 0f), Quaternion.identity);
                                        FlyEnemy fe = enemy.GetComponent<FlyEnemy>();
                                        fe.SetFacing(true);
                                    }
                                    attackCount = 2;
                                }
                            }
                                if (attackCount == 0)
                                {
                                    if (isFacingRight)
                                    {
                                        enemy = Instantiate(enemyPrefab, new Vector3(rb.position.x - 2f, rb.position.y - 1f, 0f), Quaternion.identity);
                                    }
                                    else
                                    {
                                        enemy = Instantiate(enemyPrefab, new Vector3(rb.position.x + 2f, rb.position.y - 1f, 0f), Quaternion.identity);
                                        FlyEnemy fe = enemy.GetComponent<FlyEnemy>();
                                        fe.SetFacing(true);
                                    }
                                    attackCount = 1;
                                }
                        }
                    }
                }
                else
                {
                    // æ”»æ’ƒçµ‚äº†
                    isAttacking = false; 
                    //ã‚¯ãƒ¼ãƒ«ã‚¿ã‚¤ãƒ ãƒªã‚»ãƒƒãƒˆ
                    coolTimer = coolTime;
                }
            }

        }

    }

    // ï¿½nï¿½Ê‚Æ‚ÌÚGï¿½ï¿½ï¿½ï¿½iï¿½^ï¿½Oï¿½Å”ï¿½ï¿½ï¿½j
    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Ground") || collision.gameObject.CompareTag("MoveGround"))
        {
            groundContactCount++;
            isGrounded = true;
        }
    }

    private void OnCollisionExit2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Ground") || collision.gameObject.CompareTag("MoveGround"))
        {
            groundContactCount--;
            if (groundContactCount <= 0)
            {
                groundContactCount = 0;
                isGrounded = false;
            }
        }
    }

    public void TakeDamage(int amount)
    {
        currentHealth -= amount;
        UnityEngine.Debug.Log($"BossãŒ{amount}ãƒ€ãƒ¡ãƒ¼ã‚¸ã‚’å—ã‘ãŸï¼æ®‹ã‚ŠHP: {currentHealth}");

        if (currentHealth <= 0)
        {
            Die();
        }
    }

    private void Die()
    {
        UnityEngine.Debug.Log("Bossã‚’å€’ã—ãŸï¼");

        // ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã«ãƒã‚¤ãƒ³ãƒˆåŠ ç®—
        PlayerController player = FindObjectOfType<PlayerController>();
        if (player != null)
        {
            player.AddPoint(point);
        }

        Destroy(gameObject);
    }

}