using UnityEngine;

public class WalkEnemy : MonoBehaviour,IEnemyStatus
{
    public int damage = 1;
    public float moveSpeed = 3f;    // ï¿½Gï¿½ÌˆÚ“ï¿½ï¿½ï¿½ï¿½x

    public int Damage { get; set; }
    public float MoveSpeed { get; set; }
    public float DetectRadius { get; set; }

    private Rigidbody2D rb;
    private Transform player;
    private bool isGrounded = false;
    private bool isFacingRight = false;
    private int groundContactCount = 0;

    void Start()
    {
        Damage = damage;
        MoveSpeed = moveSpeed;
        DetectRadius = 0;

        rb = GetComponent<Rigidbody2D>();

        // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Æ•ï¿½ï¿½ï¿½ï¿½Õ“Ë‚ğ–³ï¿½ï¿½ï¿½ï¿½ï¿½
        GameObject playerObj = GameObject.FindWithTag("Player");
        if (playerObj != null)
        {
            player = playerObj.transform; // Transformï¿½ÍƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ÌˆÊ’uï¿½ipositionï¿½jï¿½Aï¿½ï¿½]ï¿½irotationï¿½jï¿½Aï¿½Xï¿½Pï¿½[ï¿½ï¿½ï¿½iscaleï¿½jï¿½ï¿½ï¿½Ç—ï¿½
            Collider2D playerCol = playerObj.GetComponent<Collider2D>();
            Collider2D myCol = GetComponent<Collider2D>();
            if (playerCol != null && myCol != null)
            {
                Physics2D.IgnoreCollision(myCol, playerCol, true);
            }
        }
    }

    void FixedUpdate()
    {
        if (!isGrounded) return;

        // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ü‚Å‚Ì‹ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Z
        float distance = Vector2.Distance(transform.position, player.position);

        // ï¿½ï¿½ï¿½a detectRadius ï¿½È“ï¿½ï¿½È‚ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½xï¿½ï¿½ï¿½Wï¿½ÉŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÄˆÚ“ï¿½

        Vector2 targetPos;
        
        if (isFacingRight)
        {
            targetPos = new Vector2(rb.position.x + 1, rb.position.y); // å³å‘ãã®å ´åˆ
        }
        else
        {
            targetPos = new Vector2(rb.position.x - 1, rb.position.y); // å·¦å‘ãã®å ´åˆ
        }
        Vector2 newPos = Vector2.MoveTowards(rb.position, targetPos, moveSpeed * Time.fixedDeltaTime);
        rb.MovePosition(newPos);
        
    }

    // ï¿½nï¿½Ê‚Æ‚ÌÚGï¿½ï¿½ï¿½ï¿½iï¿½^ï¿½Oï¿½Å”ï¿½ï¿½ï¿½j
    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Ground"))
        {
            groundContactCount++;
            isGrounded = true;
            if (groundContactCount == 2) // å£ã¨åºŠã«åŒæ™‚ã«æ¥è§¦ã—ã¦ã„ã‚‹çŠ¶æ…‹
            {
                if (isFacingRight) // å³ã‚’å‘ã„ã¦ã„ã‚‹å ´åˆ
                {
                    isFacingRight = false;
                }
                else // å·¦å‘ãã®å ´åˆ
                {
                    isFacingRight = true;
                }
            }
        }
    }

    private void OnCollisionExit2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Ground"))
        {
            groundContactCount--;
            if (groundContactCount <= 0)
            {
                groundContactCount = 0;
                isGrounded = false;
            }
        }
    }
}
